name: CI
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Mamba with Python ${{ matrix.python-version }}
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: test
          create-args: >-
            -c bioconda
            python=${{ matrix.python-version }}
            biopython
            blast
            coverage
            p-tqdm
            pyfaidx
            requests
            vcfpy
            
      - name: Run Test
        run: micromamba activate test | coverage run -m unittest discover -s test
        shell: bash -el {0}

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
          env: CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
