name: CI
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Mamba with Python ${{ matrix.python-version }}
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: test
          create-args: >-
            -c bioconda
            python=${{ matrix.python-version }}
            biopython
            blast
            coverage
            p-tqdm
            pyfaidx
            requests
            vcfpy
          cache-environment: true
          cache-downloads: false
            
      - name: Run Test
        run: micromamba activate test && coverage run --source=./gdbr --omit=./test/* -m unittest discover test && coverage xml
        shell: bash -el {0}

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3